[2022-05-11 06:55:48,284] {processor.py:163} INFO - Started process (PID=28837) to work on /opt/airflow/dags/ej9.py
[2022-05-11 06:55:48,301] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 06:55:48,302] {logging_mixin.py:109} INFO - [2022-05-11 06:55:48,302] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 06:55:48,645] {logging_mixin.py:109} INFO - [2022-05-11 06:55:48,587] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:55:48,660] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 06:55:48,764] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.485 seconds
[2022-05-11 06:56:19,020] {processor.py:163} INFO - Started process (PID=28892) to work on /opt/airflow/dags/ej9.py
[2022-05-11 06:56:19,022] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 06:56:19,023] {logging_mixin.py:109} INFO - [2022-05-11 06:56:19,023] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 06:56:19,067] {logging_mixin.py:109} INFO - [2022-05-11 06:56:19,062] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:56:19,068] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 06:56:19,096] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.081 seconds
[2022-05-11 06:56:49,595] {processor.py:163} INFO - Started process (PID=28964) to work on /opt/airflow/dags/ej9.py
[2022-05-11 06:56:49,596] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 06:56:49,598] {logging_mixin.py:109} INFO - [2022-05-11 06:56:49,597] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 06:56:49,636] {logging_mixin.py:109} INFO - [2022-05-11 06:56:49,630] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:56:49,638] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 06:56:49,665] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.073 seconds
[2022-05-11 06:57:20,044] {processor.py:163} INFO - Started process (PID=29027) to work on /opt/airflow/dags/ej9.py
[2022-05-11 06:57:20,045] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 06:57:20,046] {logging_mixin.py:109} INFO - [2022-05-11 06:57:20,046] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 06:57:20,078] {logging_mixin.py:109} INFO - [2022-05-11 06:57:20,073] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:57:20,080] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 06:57:20,109] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.069 seconds
[2022-05-11 06:57:50,299] {processor.py:163} INFO - Started process (PID=29100) to work on /opt/airflow/dags/ej9.py
[2022-05-11 06:57:50,300] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 06:57:50,301] {logging_mixin.py:109} INFO - [2022-05-11 06:57:50,301] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 06:57:50,326] {logging_mixin.py:109} INFO - [2022-05-11 06:57:50,320] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:57:50,328] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 06:57:50,356] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.061 seconds
[2022-05-11 06:58:20,875] {processor.py:163} INFO - Started process (PID=29171) to work on /opt/airflow/dags/ej9.py
[2022-05-11 06:58:20,877] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 06:58:20,878] {logging_mixin.py:109} INFO - [2022-05-11 06:58:20,878] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 06:58:20,919] {logging_mixin.py:109} INFO - [2022-05-11 06:58:20,912] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:58:20,921] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 06:58:20,948] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.077 seconds
[2022-05-11 06:58:51,106] {processor.py:163} INFO - Started process (PID=29235) to work on /opt/airflow/dags/ej9.py
[2022-05-11 06:58:51,108] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 06:58:51,109] {logging_mixin.py:109} INFO - [2022-05-11 06:58:51,109] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 06:58:51,155] {logging_mixin.py:109} INFO - [2022-05-11 06:58:51,146] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:58:51,158] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 06:58:51,192] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.090 seconds
[2022-05-11 06:59:21,270] {processor.py:163} INFO - Started process (PID=29308) to work on /opt/airflow/dags/ej9.py
[2022-05-11 06:59:21,272] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 06:59:21,273] {logging_mixin.py:109} INFO - [2022-05-11 06:59:21,273] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 06:59:21,302] {logging_mixin.py:109} INFO - [2022-05-11 06:59:21,297] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:59:21,303] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 06:59:21,330] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.062 seconds
[2022-05-11 06:59:51,416] {processor.py:163} INFO - Started process (PID=29371) to work on /opt/airflow/dags/ej9.py
[2022-05-11 06:59:51,418] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 06:59:51,419] {logging_mixin.py:109} INFO - [2022-05-11 06:59:51,419] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 06:59:51,457] {logging_mixin.py:109} INFO - [2022-05-11 06:59:51,451] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 06:59:51,460] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 06:59:51,484] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.072 seconds
[2022-05-11 07:00:21,865] {processor.py:163} INFO - Started process (PID=29445) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:00:21,867] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:00:21,868] {logging_mixin.py:109} INFO - [2022-05-11 07:00:21,868] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:00:21,886] {logging_mixin.py:109} INFO - [2022-05-11 07:00:21,883] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:00:21,887] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:00:21,915] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.053 seconds
[2022-05-11 07:00:52,550] {processor.py:163} INFO - Started process (PID=29509) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:00:52,552] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:00:52,553] {logging_mixin.py:109} INFO - [2022-05-11 07:00:52,553] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:00:52,589] {logging_mixin.py:109} INFO - [2022-05-11 07:00:52,583] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:00:52,591] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:00:52,618] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.073 seconds
[2022-05-11 07:01:23,182] {processor.py:163} INFO - Started process (PID=29581) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:01:23,183] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:01:23,184] {logging_mixin.py:109} INFO - [2022-05-11 07:01:23,184] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:01:23,206] {logging_mixin.py:109} INFO - [2022-05-11 07:01:23,200] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:01:23,211] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:01:23,254] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.077 seconds
[2022-05-11 07:01:53,515] {processor.py:163} INFO - Started process (PID=29644) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:01:53,517] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:01:53,518] {logging_mixin.py:109} INFO - [2022-05-11 07:01:53,518] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:01:53,554] {logging_mixin.py:109} INFO - [2022-05-11 07:01:53,549] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:01:53,556] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:01:53,584] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.073 seconds
[2022-05-11 07:02:23,960] {processor.py:163} INFO - Started process (PID=29718) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:02:23,962] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:02:23,963] {logging_mixin.py:109} INFO - [2022-05-11 07:02:23,963] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:02:23,988] {logging_mixin.py:109} INFO - [2022-05-11 07:02:23,984] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:02:23,990] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:02:24,017] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.061 seconds
[2022-05-11 07:02:54,645] {processor.py:163} INFO - Started process (PID=29781) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:02:54,647] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:02:54,647] {logging_mixin.py:109} INFO - [2022-05-11 07:02:54,647] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:02:54,678] {logging_mixin.py:109} INFO - [2022-05-11 07:02:54,673] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:02:54,682] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:02:54,710] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.069 seconds
[2022-05-11 07:03:25,100] {processor.py:163} INFO - Started process (PID=29853) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:03:25,101] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:03:25,103] {logging_mixin.py:109} INFO - [2022-05-11 07:03:25,102] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:03:25,138] {logging_mixin.py:109} INFO - [2022-05-11 07:03:25,132] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:03:25,141] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:03:25,166] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.069 seconds
[2022-05-11 07:03:55,923] {processor.py:163} INFO - Started process (PID=29916) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:03:55,925] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:03:55,926] {logging_mixin.py:109} INFO - [2022-05-11 07:03:55,925] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:03:55,958] {logging_mixin.py:109} INFO - [2022-05-11 07:03:55,953] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:03:55,961] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:03:55,987] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.068 seconds
[2022-05-11 07:04:26,464] {processor.py:163} INFO - Started process (PID=29988) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:04:26,465] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:04:26,467] {logging_mixin.py:109} INFO - [2022-05-11 07:04:26,466] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:04:26,491] {logging_mixin.py:109} INFO - [2022-05-11 07:04:26,485] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:04:26,492] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:04:26,514] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.054 seconds
[2022-05-11 07:04:56,969] {processor.py:163} INFO - Started process (PID=30060) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:04:56,971] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:04:56,972] {logging_mixin.py:109} INFO - [2022-05-11 07:04:56,972] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:04:56,992] {logging_mixin.py:109} INFO - [2022-05-11 07:04:56,988] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:04:56,993] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:04:57,019] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.054 seconds
[2022-05-11 07:05:27,417] {processor.py:163} INFO - Started process (PID=30126) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:05:27,419] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:05:27,420] {logging_mixin.py:109} INFO - [2022-05-11 07:05:27,420] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:05:27,455] {logging_mixin.py:109} INFO - [2022-05-11 07:05:27,449] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:05:27,457] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:05:27,484] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.071 seconds
[2022-05-11 07:05:57,798] {processor.py:163} INFO - Started process (PID=30199) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:05:57,800] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:05:57,801] {logging_mixin.py:109} INFO - [2022-05-11 07:05:57,801] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:05:57,824] {logging_mixin.py:109} INFO - [2022-05-11 07:05:57,820] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:05:57,826] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:05:57,854] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.059 seconds
[2022-05-11 07:06:28,348] {processor.py:163} INFO - Started process (PID=30261) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:06:28,350] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:06:28,351] {logging_mixin.py:109} INFO - [2022-05-11 07:06:28,351] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:06:28,384] {logging_mixin.py:109} INFO - [2022-05-11 07:06:28,378] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:06:28,386] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:06:28,411] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.066 seconds
[2022-05-11 07:06:58,820] {processor.py:163} INFO - Started process (PID=30332) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:06:58,821] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:06:58,822] {logging_mixin.py:109} INFO - [2022-05-11 07:06:58,822] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:06:58,847] {logging_mixin.py:109} INFO - [2022-05-11 07:06:58,842] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:06:58,848] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:06:58,876] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.060 seconds
[2022-05-11 07:07:29,245] {processor.py:163} INFO - Started process (PID=30395) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:07:29,246] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:07:29,247] {logging_mixin.py:109} INFO - [2022-05-11 07:07:29,247] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:07:29,281] {logging_mixin.py:109} INFO - [2022-05-11 07:07:29,276] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:07:29,283] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:07:29,311] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.069 seconds
[2022-05-11 07:07:59,391] {processor.py:163} INFO - Started process (PID=30467) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:07:59,393] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:07:59,395] {logging_mixin.py:109} INFO - [2022-05-11 07:07:59,395] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:07:59,434] {logging_mixin.py:109} INFO - [2022-05-11 07:07:59,428] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:07:59,436] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:07:59,461] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.073 seconds
[2022-05-11 07:08:29,963] {processor.py:163} INFO - Started process (PID=30530) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:08:29,966] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:08:29,967] {logging_mixin.py:109} INFO - [2022-05-11 07:08:29,967] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:08:30,000] {logging_mixin.py:109} INFO - [2022-05-11 07:08:29,995] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:08:30,003] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:08:30,029] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.070 seconds
[2022-05-11 07:09:00,133] {processor.py:163} INFO - Started process (PID=30602) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:09:00,135] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:09:00,136] {logging_mixin.py:109} INFO - [2022-05-11 07:09:00,136] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:09:00,168] {logging_mixin.py:109} INFO - [2022-05-11 07:09:00,163] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:09:00,170] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:09:00,200] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.069 seconds
[2022-05-11 07:09:30,847] {processor.py:163} INFO - Started process (PID=30674) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:09:30,848] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:09:30,850] {logging_mixin.py:109} INFO - [2022-05-11 07:09:30,850] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:09:30,884] {logging_mixin.py:109} INFO - [2022-05-11 07:09:30,880] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:09:30,886] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:09:30,913] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.069 seconds
[2022-05-11 07:10:01,223] {processor.py:163} INFO - Started process (PID=30736) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:10:01,225] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:10:01,226] {logging_mixin.py:109} INFO - [2022-05-11 07:10:01,226] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:10:01,270] {logging_mixin.py:109} INFO - [2022-05-11 07:10:01,261] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:10:01,273] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:10:01,303] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.084 seconds
[2022-05-11 07:10:31,844] {processor.py:163} INFO - Started process (PID=30809) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:10:31,847] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:10:31,848] {logging_mixin.py:109} INFO - [2022-05-11 07:10:31,848] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:10:31,875] {logging_mixin.py:109} INFO - [2022-05-11 07:10:31,870] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:10:31,877] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:10:31,908] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.070 seconds
[2022-05-11 07:11:02,706] {processor.py:163} INFO - Started process (PID=30873) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:11:02,708] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:11:02,709] {logging_mixin.py:109} INFO - [2022-05-11 07:11:02,709] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:11:02,757] {logging_mixin.py:109} INFO - [2022-05-11 07:11:02,747] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:11:02,761] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:11:02,790] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.089 seconds
[2022-05-11 07:11:33,414] {processor.py:163} INFO - Started process (PID=30945) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:11:33,416] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:11:33,418] {logging_mixin.py:109} INFO - [2022-05-11 07:11:33,417] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:11:33,448] {logging_mixin.py:109} INFO - [2022-05-11 07:11:33,442] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:11:33,450] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:11:33,478] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.069 seconds
[2022-05-11 07:12:03,898] {processor.py:163} INFO - Started process (PID=31009) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:12:03,899] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:12:03,900] {logging_mixin.py:109} INFO - [2022-05-11 07:12:03,900] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:12:03,915] {logging_mixin.py:109} INFO - [2022-05-11 07:12:03,912] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:12:03,916] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:12:03,940] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.045 seconds
[2022-05-11 07:12:34,821] {processor.py:163} INFO - Started process (PID=31082) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:12:34,823] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:12:34,824] {logging_mixin.py:109} INFO - [2022-05-11 07:12:34,824] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:12:34,840] {logging_mixin.py:109} INFO - [2022-05-11 07:12:34,836] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:12:34,841] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:12:34,867] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.051 seconds
[2022-05-11 07:13:05,119] {processor.py:163} INFO - Started process (PID=31145) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:13:05,120] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:13:05,121] {logging_mixin.py:109} INFO - [2022-05-11 07:13:05,121] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:13:05,136] {logging_mixin.py:109} INFO - [2022-05-11 07:13:05,133] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:13:05,137] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:13:05,163] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.048 seconds
[2022-05-11 07:13:35,392] {processor.py:163} INFO - Started process (PID=31219) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:13:35,393] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:13:35,394] {logging_mixin.py:109} INFO - [2022-05-11 07:13:35,394] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:13:35,407] {logging_mixin.py:109} INFO - [2022-05-11 07:13:35,404] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:13:35,408] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:13:35,436] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.048 seconds
[2022-05-11 07:14:05,901] {processor.py:163} INFO - Started process (PID=31282) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:14:05,902] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:14:05,903] {logging_mixin.py:109} INFO - [2022-05-11 07:14:05,903] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:14:05,919] {logging_mixin.py:109} INFO - [2022-05-11 07:14:05,916] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:14:05,921] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:14:05,948] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.051 seconds
[2022-05-11 07:14:36,458] {processor.py:163} INFO - Started process (PID=31354) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:14:36,459] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:14:36,460] {logging_mixin.py:109} INFO - [2022-05-11 07:14:36,460] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:14:36,475] {logging_mixin.py:109} INFO - [2022-05-11 07:14:36,471] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:14:36,476] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:14:36,503] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.049 seconds
[2022-05-11 07:15:06,583] {processor.py:163} INFO - Started process (PID=31427) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:15:06,586] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:15:06,588] {logging_mixin.py:109} INFO - [2022-05-11 07:15:06,588] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:15:06,607] {logging_mixin.py:109} INFO - [2022-05-11 07:15:06,603] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:15:06,609] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:15:06,638] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.058 seconds
[2022-05-11 07:15:36,859] {processor.py:163} INFO - Started process (PID=31492) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:15:36,860] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:15:36,861] {logging_mixin.py:109} INFO - [2022-05-11 07:15:36,861] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:15:36,879] {logging_mixin.py:109} INFO - [2022-05-11 07:15:36,875] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:15:36,880] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:15:36,910] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.053 seconds
[2022-05-11 07:16:07,371] {processor.py:163} INFO - Started process (PID=31566) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:16:07,372] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:16:07,373] {logging_mixin.py:109} INFO - [2022-05-11 07:16:07,373] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:16:07,389] {logging_mixin.py:109} INFO - [2022-05-11 07:16:07,385] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:16:07,390] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:16:07,419] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.051 seconds
[2022-05-11 07:16:37,715] {processor.py:163} INFO - Started process (PID=31629) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:16:37,717] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:16:37,718] {logging_mixin.py:109} INFO - [2022-05-11 07:16:37,718] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:16:37,734] {logging_mixin.py:109} INFO - [2022-05-11 07:16:37,731] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:16:37,736] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:16:37,762] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.051 seconds
[2022-05-11 07:17:08,305] {processor.py:163} INFO - Started process (PID=31699) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:17:08,307] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:17:08,308] {logging_mixin.py:109} INFO - [2022-05-11 07:17:08,308] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:17:08,331] {logging_mixin.py:109} INFO - [2022-05-11 07:17:08,326] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:17:08,332] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:17:08,366] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.066 seconds
[2022-05-11 07:17:38,823] {processor.py:163} INFO - Started process (PID=31765) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:17:38,825] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:17:38,827] {logging_mixin.py:109} INFO - [2022-05-11 07:17:38,826] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:17:38,849] {logging_mixin.py:109} INFO - [2022-05-11 07:17:38,844] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:17:38,851] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:17:38,880] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.060 seconds
[2022-05-11 07:18:09,509] {processor.py:163} INFO - Started process (PID=31828) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:18:09,511] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:18:09,512] {logging_mixin.py:109} INFO - [2022-05-11 07:18:09,512] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:18:09,533] {logging_mixin.py:109} INFO - [2022-05-11 07:18:09,528] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:18:09,534] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:18:09,565] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.059 seconds
[2022-05-11 07:18:39,707] {processor.py:163} INFO - Started process (PID=31900) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:18:39,709] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:18:39,710] {logging_mixin.py:109} INFO - [2022-05-11 07:18:39,710] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:18:39,734] {logging_mixin.py:109} INFO - [2022-05-11 07:18:39,728] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:18:39,735] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:18:39,767] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.064 seconds
[2022-05-11 07:19:09,889] {processor.py:163} INFO - Started process (PID=31963) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:19:09,891] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:19:09,892] {logging_mixin.py:109} INFO - [2022-05-11 07:19:09,891] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:19:09,908] {logging_mixin.py:109} INFO - [2022-05-11 07:19:09,905] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:19:09,910] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:19:09,932] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.046 seconds
[2022-05-11 07:19:40,031] {processor.py:163} INFO - Started process (PID=32035) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:19:40,033] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:19:40,034] {logging_mixin.py:109} INFO - [2022-05-11 07:19:40,034] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:19:40,055] {logging_mixin.py:109} INFO - [2022-05-11 07:19:40,050] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:19:40,057] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:19:40,090] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.064 seconds
[2022-05-11 07:20:10,465] {processor.py:163} INFO - Started process (PID=32098) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:20:10,467] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:20:10,468] {logging_mixin.py:109} INFO - [2022-05-11 07:20:10,468] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:20:10,491] {logging_mixin.py:109} INFO - [2022-05-11 07:20:10,486] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:20:10,493] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:20:10,525] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.064 seconds
[2022-05-11 07:20:40,775] {processor.py:163} INFO - Started process (PID=32170) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:20:40,776] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:20:40,777] {logging_mixin.py:109} INFO - [2022-05-11 07:20:40,777] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:20:40,795] {logging_mixin.py:109} INFO - [2022-05-11 07:20:40,791] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:20:40,796] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:20:40,821] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.049 seconds
[2022-05-11 07:21:11,552] {processor.py:163} INFO - Started process (PID=32234) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:21:11,553] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:21:11,554] {logging_mixin.py:109} INFO - [2022-05-11 07:21:11,554] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:21:11,569] {logging_mixin.py:109} INFO - [2022-05-11 07:21:11,566] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:21:11,570] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:21:11,600] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.052 seconds
[2022-05-11 07:21:41,756] {processor.py:163} INFO - Started process (PID=32305) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:21:41,757] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:21:41,758] {logging_mixin.py:109} INFO - [2022-05-11 07:21:41,758] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:21:41,774] {logging_mixin.py:109} INFO - [2022-05-11 07:21:41,771] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:21:41,776] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:21:41,807] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.054 seconds
[2022-05-11 07:22:11,946] {processor.py:163} INFO - Started process (PID=32368) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:22:11,948] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:22:11,949] {logging_mixin.py:109} INFO - [2022-05-11 07:22:11,948] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:22:11,963] {logging_mixin.py:109} INFO - [2022-05-11 07:22:11,960] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:22:11,964] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:22:11,991] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.048 seconds
[2022-05-11 07:22:42,334] {processor.py:163} INFO - Started process (PID=32441) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:22:42,336] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:22:42,337] {logging_mixin.py:109} INFO - [2022-05-11 07:22:42,337] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:22:42,354] {logging_mixin.py:109} INFO - [2022-05-11 07:22:42,351] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:22:42,355] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:22:42,380] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.049 seconds
[2022-05-11 07:23:12,472] {processor.py:163} INFO - Started process (PID=32503) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:23:12,475] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:23:12,476] {logging_mixin.py:109} INFO - [2022-05-11 07:23:12,476] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:23:12,504] {logging_mixin.py:109} INFO - [2022-05-11 07:23:12,498] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:23:12,506] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:23:12,537] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.070 seconds
[2022-05-11 07:23:42,911] {processor.py:163} INFO - Started process (PID=32575) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:23:42,913] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:23:42,915] {logging_mixin.py:109} INFO - [2022-05-11 07:23:42,914] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:23:42,933] {logging_mixin.py:109} INFO - [2022-05-11 07:23:42,929] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:23:42,934] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:23:42,964] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.058 seconds
[2022-05-11 07:24:13,365] {processor.py:163} INFO - Started process (PID=32638) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:24:13,367] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:24:13,368] {logging_mixin.py:109} INFO - [2022-05-11 07:24:13,368] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:24:13,395] {logging_mixin.py:109} INFO - [2022-05-11 07:24:13,388] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:24:13,397] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:24:13,438] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.080 seconds
[2022-05-11 07:24:44,240] {processor.py:163} INFO - Started process (PID=32712) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:24:44,242] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:24:44,243] {logging_mixin.py:109} INFO - [2022-05-11 07:24:44,243] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:24:44,263] {logging_mixin.py:109} INFO - [2022-05-11 07:24:44,259] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:24:44,265] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:24:44,298] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.063 seconds
[2022-05-11 07:25:14,488] {processor.py:163} INFO - Started process (PID=307) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:25:14,490] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:25:14,491] {logging_mixin.py:109} INFO - [2022-05-11 07:25:14,491] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:25:14,509] {logging_mixin.py:109} INFO - [2022-05-11 07:25:14,505] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:25:14,511] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:25:14,534] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.048 seconds
[2022-05-11 07:25:44,784] {processor.py:163} INFO - Started process (PID=369) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:25:44,785] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:25:44,786] {logging_mixin.py:109} INFO - [2022-05-11 07:25:44,786] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:25:44,800] {logging_mixin.py:109} INFO - [2022-05-11 07:25:44,797] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:25:44,801] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:25:44,828] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.047 seconds
[2022-05-11 07:26:15,213] {processor.py:163} INFO - Started process (PID=443) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:26:15,214] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:26:15,215] {logging_mixin.py:109} INFO - [2022-05-11 07:26:15,215] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:26:15,230] {logging_mixin.py:109} INFO - [2022-05-11 07:26:15,227] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:26:15,231] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:26:15,255] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.045 seconds
[2022-05-11 07:26:45,977] {processor.py:163} INFO - Started process (PID=517) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:26:45,979] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:26:45,979] {logging_mixin.py:109} INFO - [2022-05-11 07:26:45,979] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:26:45,994] {logging_mixin.py:109} INFO - [2022-05-11 07:26:45,992] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:26:45,995] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:26:46,015] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.040 seconds
[2022-05-11 07:27:16,741] {processor.py:163} INFO - Started process (PID=580) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:27:16,743] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:27:16,743] {logging_mixin.py:109} INFO - [2022-05-11 07:27:16,743] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:27:16,757] {logging_mixin.py:109} INFO - [2022-05-11 07:27:16,754] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:27:16,758] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:27:16,779] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.041 seconds
[2022-05-11 07:27:46,813] {processor.py:163} INFO - Started process (PID=653) to work on /opt/airflow/dags/ej9.py
[2022-05-11 07:27:46,815] {processor.py:642} INFO - Processing file /opt/airflow/dags/ej9.py for tasks to queue
[2022-05-11 07:27:46,816] {logging_mixin.py:109} INFO - [2022-05-11 07:27:46,815] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ej9.py
[2022-05-11 07:27:46,832] {logging_mixin.py:109} INFO - [2022-05-11 07:27:46,828] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ej9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ej9.py", line 3, in <module>
    from airflow.providers.apache.pig.operators.pig import PigOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2022-05-11 07:27:46,833] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ej9.py
[2022-05-11 07:27:46,857] {processor.py:171} INFO - Processing /opt/airflow/dags/ej9.py took 0.047 seconds
